name: fire_base_project
description: "Attendance App with Firebase"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.18.1
  get_storage: ^2.1.1
  google_fonts: ^6.3.2
  flutter_dotenv: ^6.0.0

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # UI & Utils
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.3
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  fl_chart: ^0.70.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/
    - assets/images/
    - assets/lottie/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.jpg"
  adaptive_icon_background: "#E3F2FD"
  adaptive_icon_foreground: "assets/images/splash_logo.jpg"

flutter_native_splash:
  color: "#1E88E5"
  image: assets/images/splash_logo.jpg
  color_dark: "#121212"
  image_dark: "assets/images/splash_logo_dark.jpg"
  ios_content_mode: "center"
  android_gravity: center
  web: false